services:
  backend:
    image: haenck/hsr-warptracker-backend:latest # dont change
    container_name: hsr-backend
    volumes:
      - ${DB_PATH}:/app/db.sqlite3 # change the path to actual db
      - ${MEDIA_PATH}:/app/media # change path to acutal media folder
    ports:
      - "8000:8000" # dont change
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS} # * for allow all
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS} # url and port react is running
  
  frontend:
    image: haenck/hsr-warptracker-frontend:latest # dont change
    container_name: hsr-frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "5173:80" # dont change