services:
  backend:
    image: haenck/hsr-warptracker-backend:latest
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1 # * for allow all
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
  
  frontend:
    image: haenck/hsr-warptracker-frontend:latest
    ports:
      - "5173:80"